"""
The config file that controls all the parameters for the file
"""

import os

FRAMEWORK = {
	# The project uses the stable B/C plugin interfaces exclusively.
	'EVALUATION_MODE': os.getenv('UKNIT_EVALUATION_MODE', 'plugins').strip().lower(),
}

# Structural dimensions used to build compact, runtime-specific LLM prompts.
# They describe the existing 64-bit/4-bit construction and are not model
# controls; the current generation remains the source of truth for round count.
CIPHER_STRUCTURE = {
    'STATE_BITS': 64,
    'CELL_BITS': 4,
}

# Team C performance measurement.  OpenLane is mandatory in plugin mode;
# leave COMMAND empty to auto-detect ``openlane`` or ``wsl openlane``.
OPENLANE = {
    # Set to false to skip OpenLane and use the explicit latency placeholder
    # (1.0 ns) for fast LLM/search smoke runs.
    'ENABLED': os.getenv('UKNIT_OPENLANE_ENABLED', 'false').strip().lower()
        in {'1', 'true', 'yes', 'on'},
    'COMMAND': os.getenv('UKNIT_OPENLANE_COMMAND', '').strip(),
    'WORK_ROOT': os.getenv('UKNIT_OPENLANE_WORK_ROOT', '').strip(),
    'TIMEOUT_SECONDS': int(os.getenv('UKNIT_OPENLANE_TIMEOUT_SECONDS', '3600')),
    'CLOCK_PERIOD_NS': float(os.getenv('UKNIT_OPENLANE_CLOCK_PERIOD_NS', '10.0')),
}

HYPERPARAMETERS = { # GENERIC_SETTINGS
	'POPULATION_SIZE' : 1, ######30, # 200 # poplutationSize
	# 'MAX_GENERATION': [0,0,0,100,100,100,100,100,100,100,100,100,100], # starting from round 3
	'MAX_GENERATION': [1,1,2,2,2,2,5,5,5,5,5,5,5], # for testing purposes
	'MAX_NUM_ROUNDS' : 4, ######12, # number of rounds for the cipher
	'NUM_OF_THREADS' : 4, #####30, # number of threads
}

# Elite retention is independent of structural actions. The LLM decides every
# crossover and mutation action for the next candidate pool.
SEARCH_SETTINGS = {
	'NUM_FIT_CIPHERS' : 1,
}

INIT_SETTINGS = {
	'INIT_NUM_ROUNDS' : 3, # 3 # initNumRounds
	'SBOX' : { # SBOX_SETTINGS
		'MANTIS_ONLY' : True, # mantis 优先判断这个
		'MAX_4_DIFF_UNIFORMITY' : False, # the set of sboxes with differential uniformity of maximum 4
	},
	'PERMUTATION' : {
		'MIXCOLUMNS' : { # the program assumes these sum to 1 # uniform
			'PRINCE_LIKE': 0.5,
			'MIDORI_LIKE': 0.5,
		},
    },
    'INCLUDE_PRINCE' : False, # include prince as one of the candidates?
    'INCLUDE_UKNIT' : False, # include uknitbe as one of the candidates?
    # Optional precomputed uKNIT-BC baseline.  The original implementation
    # loads this complete cipher from a pickle because it is not generated by
    # the random initializer in this repository.
    'UKNIT_BASELINE_PATH' : os.getenv('UKNIT_BASELINE_PATH', '').strip(),
    # When the baseline is unavailable, keep smoke/search runs usable by
    # constructing a fresh random candidate with the same round shape.  Set
    # UKNIT_FALLBACK_RANDOM=false to require the real baseline file.
    'UKNIT_FALLBACK_RANDOM' : os.getenv(
        'UKNIT_FALLBACK_RANDOM', 'true'
    ).strip().lower() not in {'0', 'false', 'no', 'off'},
}

# Team B security analysis used by the active plugin path.  The environment
# variables are read here so the run configuration copied into ``runs/``
# records the exact solver and timeout values used for that experiment.
SECURITY_ANALYSIS = {
    'SOLVER': os.getenv('UKNIT_B_SOLVER', 'kissat').strip() or 'kissat',
    'SINGLE_QUERY_TIMEOUT_S': float(
        os.getenv('UKNIT_B_SINGLE_QUERY_TIMEOUT_S', '30')
    ),
    'TOTAL_TIMEOUT_S_PER_MODE': float(
        os.getenv('UKNIT_B_TOTAL_TIMEOUT_S_PER_MODE', '300')
    ),
    'MAXIMUM_WEIGHT': os.getenv('UKNIT_B_MAXIMUM_WEIGHT', 'auto').strip() or 'auto',
}



FITNESS_SETTINGS = {
	'FITNESS_FORMULA' : [0,0,0,
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 2086.48 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 2782.61 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 3411.64 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 4140.50 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 4732.10 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 5522.25 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 6368.43 else 0),
					  lambda sec,lat,rd: sec**2/lat + (-100 if lat > 6950.33 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 7646.79 else 0),
                      lambda sec,lat,rd: sec**2/lat + (-100 if lat > 8349.53 else 0),
					]
}
